# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f6bca656ca0d483004f97149ccb361cf7412ffe21b1cf825e274d940ea331dd94ab383554943c00873cb957d393c500a4dc503d3855d565b8048a7ae5208a2c

test:
  secret_key_base: 5d7c982e24c225c7133dd5382df8feacdac0d80cc49f1bd1845ff23573776f077e9153c829894106f70da64a4f13376b2b9542ede4fe9008eb1d7a7c03e81ae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
